package program6;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.ListIterator;
public class RemoveDuplicates {
	
	public static void main(String[] args) {
	ArrayList<String> namelist=new ArrayList<>();
            ArrayList<String> l;
	        l.add("aaa");  
	        l.add("aaa");  
	        l.add("ddd");  
	        l.add("kkk");  
	}
	
	        //System.out.println(l.toString()); 
	       // char[] s;
	        //Object add;
	        //Iterator it = add.();
	        //System.out.println(s);  
	       //Iterator<String> iterator = list.iterator();
	       
	{
	        	
	        	{
	        		  iterator it = new iterator ();
	      	        while (iterator.hasNext()) {

	      	            if (List.contains(iterator.next())) {
	      	            
	      	                iterator.remove(); 
	      	            
	      	            }
	      	        }
	      	               
	      	        
	        	
	      	          
	      	                	
	      	                	      
	      	        
	      	        
	      	              	
	        	
	       
	      	            
	      	        
	        	


	      	           
	        	
	      	       		
	      	            
	      	        
	        			
	        		
	        	
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	        		
	  .
	        
	
	



				
	


